apiVersion: v1
kind: Namespace
metadata:
  name: gamdevseg
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gam-dev-cosmoapi
  namespace: gamdevseg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gam-dev-cosmoapi
  template:
    metadata:
      labels:
        app: gam-dev-cosmoapi
    spec:
      containers:
      - name: gam-dev-cosmoapi
        image: cosmoapi:v1
        command: ["npm", "start"]
        ports:
        - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: gam-dev-cosmoapi
  namespace: gamdevseg
spec:
  selector:
    app: gam-dev-cosmoapi
  ports:
  - port: 3001
    targetPort: 3001
    nodePort: 30003
  type: NodePort
